using DatabaseConnector.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace DatabaseConnector.DAO.Entity
{
    [Table("WorkFlow")]
    public class WorkFlow
    {
        [JsonPropertyName("id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        //申请人
        [JsonPropertyName("applicant")]
        [Required]
        public string Applicant { get; set; }
        [JsonPropertyName("content")]
        [Required]
        // list of chemicals. generated by parser.
        public string Content { get; set; }
        [JsonPropertyName("startTime")]
        public DateTime StartTime { get; set; }
        [JsonPropertyName("state")]
        public string State { get; set; } = "None";
    }
}
