using DatabaseConnector.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DatabaseConnector.DAO.Entity
{
    [Table("WorkFlow")]
    public class WorkFlow
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        //申请人
        [Required]
        public string Applicant { get; set; }
        [Required]
        // list of chemicals. generated by parser.
        public string Content { get; set; }
        public DateTime StartTime { get; set; }
        public string State { get; set; } = "None";
    }
}
